Script started on Wed May 15 19:50:37 2019
[r[m[2J[H[?7h[?1;4;6l[?1049h[4l[?1h=[0m(B[1;24r[H[2J[23B[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m[1m[38;5;0m[48;5;3m[90m 0*deploy [0m[38;5;7m[48;5;0m  1 left  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][H[39m[49m[H[2J[1m[38;5;4m[94m~[0m$ sudo rbd --cluster left mirror image status mirror/mycirros
mycirros:my
global_id:   2fb96834-088e-4b3d-9784-5b087440b080  
state:[7Cup+stopped  
description: local image is primary  
last_update: 2019-05-15 19:49:44
[1m[38;5;4m[94m~[0m$
[1m[38;5;4m[94m~[0m$
[1m[38;5;4m[94m~[0m$ sudo rbd --cluster right mirror image status mirror/mycirros
mycirros:my
global_id:   2fb96834-088e-4b3d-9784-5b087440b080  
state:[7Cup+replaying  
description: replaying, master_position=[object_number=2, tag_tid=12, entry_tid=130], mirror_position=[object_number=2, tag_tid=12, entry_tid=130], entries_behind_master=0hi
last_update: 2019-05-15 19:49:58
[1m[38;5;4m[94m~[0m$[7B[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m[1m[38;5;0m[48;5;3m[90m 0*deploy [0m[38;5;7m[48;5;0m  1 left  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][17;3H[39m[49m[7B[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m[1m[38;5;0m[48;5;3m[90m 0*deploy [0m[38;5;7m[48;5;0m  1 left  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][17;3H[39m[49m [H[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[1m[38;5;2m[92m[38;5;4m[94m~[0m$ [23B[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m0 deploy  [1m[38;5;0m[48;5;3m[90m 1*left [0m[38;5;7m[48;5;0m  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][1;4H[39m[49m[H[2J[1m[38;5;4m[94m~[0m$ sudo ceph -s
sudo: unable to resolve host alicesu
cluster:[6D
id:[5C2f39d463-f9b8-40ba-af7c-017b80f0c1e2[5;5Hhealth: HEALTH_OK  

services:[7D
mon:[8C3 daemons, quorum alice,bob,charlie[9;5Hmgr:[8Calice(active), standbys: charlie, bob[49D
osd:[8C3 osds: 3 up, 3 in[30D
rbd-mirror: 1 daemon active  

data:
pools:   1 pools, 64 pgs[24D
objects: 1.33k objects, 4.27GiB[31D
usage:   8.91GiB used, 36.1GiB / 45.0GiB avail[46D
pgs:[5C64 active+clean  

io:
client:   2.25KiB/s rd, 0B/s wr, 2op/s rd, 0op/s wr

[1m[38;5;4m[94m~[0m$

[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m0 deploy  [1m[38;5;0m[48;5;3m[90m 1*left [0m[38;5;7m[48;5;0m  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][22;3H[39m[49m

[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m0 deploy  [1m[38;5;0m[48;5;3m[90m 1*left [0m[38;5;7m[48;5;0m  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:50[38;5;2m][22;3H[39m[49m [H[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K
[K[H[1m[38;5;2m[92m[38;5;4m[94m~[0m$ sudo qemu-system-x86_64 -m 128 \
>   -drive format=raw,file=rbd:mirror/mycirros,if=virtio,cache=writeback \
>   -serial stdio -nographic -monitor none
sudo: unable to resolve host alice
warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
[    0.000000] Initializing cgroup subsys cpuset
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Linux version 3.2.0-80-virtual (buildd@batsu) (gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) ) #116-Ubuntu SMP Mon Mar 23 17:28:52 UTC 2015 (Ubuntu 3.2.0-80.116-virtual 3.2.68)
[    0.000000] Command line: LABEL=cirros-rootfs ro console=tty1 console=ttyS0
[    0.000000] KERNEL supported cpus:
[    0.000000]   Intel GenuineIntel
[    0.000000]   AMD AuthenticAMD
[    0.000000]   Centaur CentaurHauls
[    0.000000] BIOS-provided physical RAM map:
[    0.000000]  BIOS-e820: 0000000000000000 - 000000000009fc00 (usable)
[    0.000000]  BIOS-e820: 000000000009fc00 - 00000000000a0000 (reserved)
[    0.000000]  BIOS-e820: 00000000000f0000 - 0000000000100000 (reserved)
[    0.000000]  BIOS-e820: 0000000000100000 - 0000000007fe0000 (usable)
[    0.000000]  BIOS-e820: 0000000007fe0000 - 0000000008000000 (reserved)
[    0.000000]  BIOS-e820: 00000000fffc0000 - 0000000100000000 (reserved)
[    0.000000] NX (Execute Disable) protection: active[1;23r[23;1H
[    0.000000] SMBIOS 2.8 present.
[    0.000000] No AGP bridge found
[    0.000000] last_pfn = 0x7fe0 max_arch_pfn = 0x400000000
[    0.000000] x86 PAT enabled: cpu 0, old 0x7040600070406, new 0x7010600070106
[    0.000000] found SMP MP-table at [ffff8800000f6630] f6630
[    0.000000] init_memory_mapping: 0000000000000000-0000000007fe0000
[    0.000000] RAMDISK: 07c71000 - 07fd0000
[    0.000000] ACPI: RSDP 00000000000f6450 00014 (v00 BOCHS )
[    0.000000] ACPI: RSDT 0000000007fe16ee 00034 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACP 0000000007fe0c14 00074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[    0.000000] ACPI: DSDT 0000000007fe0040 00BD4 (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: FACS 0000000007fe0000 00040
[    0.000000] ACPI: SSDT 0000000007fe0c88 009B6 (v01 BOCHS  BXPCSSDT 00000001 BXPC 00000001)
[    0.000000] ACPI: APIC 0000000007fe163e 00078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[    0.000000] ACPI: HPET 0000000007fe16b6 00038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[    0.000000] No NUMA configuration found
[    0.000000] Faking a node at 0000000000000000-0000000007fe0000
[    0.000000] Initmem setup node 0 0000000000000000-0000000007fe0000
[    0.000000]   NODE_DATA [0000000007fd8000 - 0000000007fdcfff]
[    0.000000] Zone PFN ranges:
[    0.000000]   DMA      0x00000010 -> 0x00001000
[    0.000000]   DMA32    0x00001000 -> 0x00100000
[    0.000000]   Normal   empty
[    0.000000] Movable zone start PFN for each node
[    0.000000] early_node_map[2] active PFN ranges
[    0.000000]     0: 0x00000010 -> 0x0000009f
[    0.000000]     0: 0x00000100 -> 0x00007fe0
[    0.000000] ACPI: PM-Timer IO Port: 0x608
[    0.000000] ACPI: LAPIC (acpi_id[0x00] lapic_id[0x00] enabled)
[    0.000000] ACPI: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[    0.000000] ACPI: IOAPIC (id[0x00] address[0xfec00000] gsi_base[0])
[    0.000000] IOAPIC[0]: apic_id 0, version 17, address 0xfec00000, GSI 0-23
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[    0.000000] ACPI: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[    0.000000] Using ACPI (MADT) for SMP configuration information
[    0.000000] ACPI: HPET id: 0x8086a201 base: 0xfed00000
[    0.000000] SMP: Allowing 1 CPUs, 0 hotplug CPUs
[    0.000000] PM: Registered nosave memory: 000000000009f000 - 00000000000a0000
[    0.000000] PM: Registered nosave memory: 00000000000a0000 - 00000000000f0000
[    0.000000] PM: Registered nosave memory: 00000000000f0000 - 0000000000100000
[    0.000000] Allocating PCI resources starting at 8000000 (gap: 8000000:f7fc0000)
[    0.000000] Booting paravirtualized kernel on bare hardware
[    0.000000] setup_percpu: NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[    0.000000] PERCPU: Embedded 27 pages/cpu @ffff880007a00000 s78848 r8192 d23552 u2097152
[    0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 32106
[    0.000000] Policy zone: DMA32
[    0.000000] Kernel command line: LABEL=cirros-rootfs ro console=tty1 console=ttyS0
[    0.000000] PID hash table entries: 512 (order: 0, 4096 bytes)
[    0.000000] Checking aperture...
[    0.000000] No AGP bridge found
[    0.000000] Memory: 109112k/130944k available (6576k kernel code, 452k absent, 21380k reserved, 6620k data, 928k init)
[    0.000000] SLUB: Genslabs=15, HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Hierarchical RCU implementation.
[    0.000000]  RCU dyntick-idle grace-period acceleration is enabled.
[    0.000000] NR_IRQS:4352 nr_irqs:256 16
[    0.000000] Console: colour VGA+ 80x25
[    0.000000] console [tty1] enabled
[    0.000000] console [ttyS0] enabled
[    0.000000] allocated 1048576 bytes of page_cgroup
[    0.000000] please try 'cgroup_disable=memory' option if you don't want memory cgroups
[    0.000000] Fast TSC calibration using PIT
[    0.000000] Detected 2598.688 MHz processor.
[    0.012653] Calibrating delay loop (skipped), value calculated using timer frequency.. 5197.37 BogoMIPS (lpj=10394752)
[    0.013548] pid_max: default: 32768 minimum: 301
[    0.019152] Security Framework initialized
[    0.021702] AppArmor: AppArmor initialized
[    0.021922] Yama: becoming mindful.
[    0.025837] Dentry cache hash table entries: 16384 (order: 5, 131072 bytes)
[    0.026782] Inode-cache hash table entries: 8192 (order: 4, 65536 bytes)
[    0.027690] Mount-cache hash table entries: 256
[    0.039148] Initializing cgroup subsys cpuacct
[    0.039539] Initializing cgroup subsys memory
[    0.040299] Initializing cgroup subsys devices
[    0.040581] Initializing cgroup subsys freezer
[    0.040816] Initializing cgroup subsys blkio
[    0.041071] Initializing cgroup subsys perf_event
[    0.043183] mce: CPU supports 10 MCE banks
[    0.044743] SMP alternatives: switching to UP code
[    0.313546] Freeing SMP alternatives: 24k freed
[    0.316537] ACPI: Core revision 20110623
[    0.343668] ftrace: allocating 26610 entries in 105 pages
[    0.371467] ..TIMER: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[    0.415112] CPU0: AMD QEMU Virtual CPU version 2.5+ stepping 03
[    0.420025] APIC calibration not consistent with PM-Timer: 111ms instead of 100ms
[    0.420025] APIC delta adjusted to PM-Timer: 6250029 (6997667)
[    0.421385] Performance Events: Broken PMU hardware detected, using software events only.
[    0.432348] NMI watchdog disabled (cpu0): hardware events not enabled
[    0.435663] Brought up 1 CPUs
[    0.436198] Total of 1 processors activated (5197.37 BogoMIPS).
[    0.454124] devtmpfs: initialized
[    0.476374] EVM: security.selinux
[    0.477851] EVM: security.SMACK64
[    0.479332] EVM: security.capability
[    0.492292] print_constraints: dummy: 
[    0.494798] RTC time: 19:50:54, date: 05/15/19
[    0.497414] NET: Registered protocol family 16
[    0.504591] ACPI: bus type pci registered
[    0.508406] PCI: Using configuration type 1 for base access
[    0.524092] bio: create slab <bio-0> at 0
[    0.528317] ACPI: Added _OSI(Module Device)
[    0.529843] ACPI: Added _OSI(Processor Device)
[    0.531414] ACPI: Added _OSI(3.0 _SCP Extensions)
[    0.532065] ACPI: Added _OSI(Processor Aggregator Device)
[    0.560834] ACPI: Interpreter enabled
[    0.562633] ACPI: (supports S0 S3 S4 S5)
[    0.565593] ACPI: Using IOAPIC for interrupt routing
[    0.601726] ACPI: No dock devices found.
[    0.603503] HEST: Table not found.
[    0.604166] PCI: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[    0.609635] ACPI: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[    0.613729] pci_root PNP0A03:00: host bridge window [io  0x0000-0x0cf7]
[    0.616092] pci_root PNP0A03:00: host bridge window [io  0x0d00-0xffff]
[    0.620133] pci_root PNP0A03:00: host bridge window [mem 0x000a0000-0x000bffff]
[    0.624071] pci_root PNP0A03:00: host bridge window [mem 0x08000000-0xfebfffff]
[    0.634114] pci 0000:00:01.3: quirk: [io  0x0600-0x063f] claimed by PIIX4 ACPI
[    0.634465] pci 0000:00:01.3: quirk: [io  0x0700-0x070f] claimed by PIIX4 SMB
[    0.976400]  pci0000:00: Unable to request _OSC control (_OSC support mask: 0x1e)
[    1.001755] ACPI: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[    1.005640] ACPI: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[    1.008991] ACPI: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[    1.012317] ACPI: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[    1.015166] ACPI: PCI Interrupt Link [LNKS] (IRQs *9)
[    1.021468] vgaarb: device added: PCI:0000:00:02.0,decodes=io+mem,owns=io+mem,locks=none
[    1.024183] vgaarb: loaded
[    1.025413] vgaarb: bridge control possible 0000:00:02.0
[    1.029736] i2c-core: driver [aat2870] using legacy suspend method
[    1.032102] i2c-core: driver [aat2870] using legacy resume method
[    1.037021] SCSI subsystem initialized
[    1.040614] usbcore: registered new interface driver usbfs
[    1.043357] usbcore: registered new interface driver hub
[    1.044568] usbcore: registered new device driver usb
[    1.050013] PCI: Using ACPI for IRQ routing
[    1.059165] NetLabel: Initializing
[    1.060100] NetLabel:  domain hash size = 128
[    1.061915] NetLabel:  protocols = UNLABELED CIPSOv4
[    1.065160] NetLabel:  unlabeled traffic allowed by default
[    1.069069] HPET: 3 timers in total, 0 timers will be used for per-cpu timer
[    1.072410] hpet0: at MMIO 0xfed00000, IRQs 2, 8, 0
[    1.074783] hpet0: 3 comparators, 64-bit 100.000000 MHz counter
[    1.085988] Switching to clocksource hpet
[    1.197021] AppArmor: AppArmor Filesystem Enabled
[    1.197979] pnp: PnP ACPI init
[    1.198345] ACPI: bus type pnp registered
[    1.208768] pnp: PnP ACPI: found 11 devices
[    1.208993] ACPI: ACPI bus type pnp unregistered
[    1.240310] NET: Registered protocol family 2
[    1.256920] IP route cache hash table entries: 1024 (order: 1, 8192 bytes)
[    1.261185] TCP established hash table entries: 4096 (order: 4, 65536 bytes)
[    1.261745] TCP bind hash table entries: 4096 (order: 4, 65536 bytes)
[    1.262208] TCP: Hash tables configured (established 4096 bind 4096)
[    1.262548] TCP reno registered
[    1.262819] UDP hash table entries: 128 (order: 0, 4096 bytes)
[    1.263233] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes)
[    1.264898] NET: Registered protocol family 1
[    1.265329] pci 0000:00:00.0: Limiting direct PCI/PCI transfers
[    1.265701] pci 0000:00:01.0: PIIX3: Enabling Passive Release
[    1.266155] pci 0000:00:01.0: Activating ISA DMA hang workarounds
[    1.277064] Trying to unpack rootfs image as initramfs...
[    1.291022] audit: initializing netlink socket (disabled)
[    1.292527] type=2000 audit(1557949854.288:1): initialized
[    1.445324] HugeTLB registered 2 MB page size, pre-allocated 0 pages
[    1.478203] VFS: Disk quotas dquot_6.5.2
[    1.478923] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    1.487007] fuse init (API version 7.17)
[    1.488567] msgmni has been set to 213
[    1.517293] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 253)
[    1.518138] io scheduler noop registered
[    1.518396] io scheduler deadline registered (default)
[    1.518962] io scheduler cfq registered
[    1.520969] pci_hotplug: PCI Hot Plug PCI Core version: 0.5
[    1.522163] pciehp: PCI Express Hot Plug Controller Driver version: 0.4
[    1.525369] input: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[    1.526203] ACPI: Power Button [PWRF]
[    1.550390] ERST: Table is not found!
[    1.550619] GHES: HEST is not enabled!
[    1.557182] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
[    1.557645] virtio-pci 0000:00:04.0: PCI INT A -> Link[LNKD] -> GSI 11 (level, high) -> IRQ 11
[    1.564608] Serial: 8250/16550 driver, 32 ports, IRQ sharing enabled
[    1.588693] serial8250: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.664113] 00:06: ttyS0 at I/O 0x3f8 (irq = 4) is a 16550A
[    1.698953] Linux agpgart interface v0.103
[    1.759059] brd: module loaded
[    1.787166] loop: module loaded
[    1.813677]  vda: vda1
[    1.860873] scsi0 : ata_piix
[    1.862602] scsi1 : ata_piix
[    1.863420] ata1: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc080 irq 14
[    1.863790] ata2: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc088 irq 15
[    1.869229] Fixed MDIO Bus: probed
[    1.869714] tun: Universal TUN/TAP device driver, 1.6
[    1.869958] tun: (C) 1999-2004 Max Krasnyansky <maxk@qualcomm.com>
[    1.871399] PPP generic driver version 2.4.2
[    1.876731] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    1.877207] ohci_hcd: USB 1.1 'Open' Host Controller (OHCI) Driver
[    1.877716] uhci_hcd: USB Universal Host Controller Interface driver
[    1.878462] usbcore: registered new interface driver libusual
[    1.879503] i8042: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[    1.882824] serio: i8042 KBD port at 0x60,0x64 irq 1
[    1.883254] serio: i8042 AUX port at 0x60,0x64 irq 12
[    1.898722] mousedev: PS/2 mouse device common for all mice
[    1.902411] input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[    1.903847] rtc_cmos 00:01: RTC can wake from S4
[    1.907000] rtc_cmos 00:01: rtc core: registered rtc_cmos as rtc0
[    1.907861] rtc0: alarms up to one day, 114 bytes nvram, hpet irqs
[    1.909101] device-mapper: uevent: version 1.0.3
[    1.916494] device-mapper: ioctl: 4.22.0-ioctl (2011-10-19) initialised: dm-devel@redhat.com
[    1.917424] cpuidle: using governor ladder
[    1.917713] cpuidle: using governor menu
[    1.917909] EFI Variables Facility v0.08 2004-May-17
[    1.922029] TCP cubic registered
[    1.923260] NET: Registered protocol family 10
[    1.931379] NET: Registered protocol family 17
[    1.931717] Registering the dns_resolver key type
[    1.950271] registered taskstats version 1
[    2.027730] Freeing initrd memory: 3452k freed
[    2.052091] ata2.00: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[    2.063517] ata2.00: configured for MWDMA2
[    2.071688] scsi 1:0:0:0: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[    2.077670] sr0: scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[    2.078073] cdrom: Uniform CD-ROM driver Revision: 3.20
[    2.081469] sr 1:0:0:0: Attached scsi generic sg0 type 5
[    2.176960]   Magic number: 3:923:849
[    2.177419] graphics fbcon: hash matches
[    2.178226] rtc_cmos 00:01: setting system clock to 2019-05-15 19:50:55 UTC (1557949855)
[    2.178725] powernow-k8: Processor cpuid 663 not supported
[    2.180373] BIOS EDD facility v0.16 2004-Jun-25, 0 devices found
[    2.180663] EDD information not available.
[    2.200994] Freeing unused kernel memory: 928k freed
[    2.223769] Write protecting the kernel read-only data: 12288k
[    2.264493] Freeing unused kernel memory: 1596k freed
[    2.295352] Freeing unused kernel memory: 1184k freed
[    2.297545] Refined TSC clocksource calibration: 2598.699 MHz.
[    2.297976] Switching to clocksource tsc

info: initramfs: up at 2.38
NOCHANGE: partition 1 is size 4176900. it cannot be grown
info: initramfs loading root from /dev/vda1
info: /etc/init.d/rc.sysinit: up at 3.32
info: container: none
Starting logging: OK
modprobe: module virtio_blk not found in modules.dep
modprobe: module virtio_net not found in modules.dep
[    4.257515] ACPI: PCI Interrupt Link [LNKC] enabled at IRQ 10
WARN: /etc/rc3.d/S10-load-modules failed
Initializing random number generator... done.
Starting acpid: OK
cirros-ds 'local' up at 5.11
no results found for mode=local. up 5.51. searched: nocloud configdrive ec2
Starting network...
[24;1H[7m[27m[38;5;2m[48;5;0m[92m[deploy[38;5;2m][            [38;5;7m0 deploy  [1m[38;5;0m[48;5;3m[90m 1*left [0m[38;5;7m[48;5;0m  2 right             [38;5;2m][[38;5;4m[94m2019-05-15 [38;5;7m[97m19:51[38;5;2m][A[39m[49mudhcpc (v1.20.1) started
Sending discover...
Sending select for 10.0.2.15...
Lease of 10.0.2.15 obtained, lease time 86400
cirros-ds 'net' up at 6.46
checking http://169.254.169.254/2009-04-04/instance-id
successful after 1/20 tries: up 6.65. iid=i-00001673
found datasource (ec2, net)
cirros-apply-net already run per instance
check-version already run per instance
Top of dropbear init script
Starting dropbear sshd: remove-dropbear-host-keys already run per instance
WARN: generating key of type ecdsa failed!
OK
userdata already run per instance
=== system information ===
Platform: QEMU Standard PC (i440FX + PIIX, 1996)
Container: none
Arch: x86_64
CPU(s): 1 @ 2598.688 MHz
Cores/Sockets/Threads: 1/1/1
Virt-type: AMD-V
RAM Size: 113MB
Disks:
NAME MAJ:MIN       SIZE LABEL         MOUNTPOINT
vda  253:0   2147483648               
vda1 253:1   2138572800 cirros-rootfs /
sr0   11:0   1073741312               
=== sshd host keys ===
-----BEGIN SSH HOST KEY KEYS-----
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgmHtfIEW6LEy2s+wmX7iT4RNGlJWRmgW9qYSGw4tNLnfc4udFUn5AyhctmqcJwtQPNr7eV7MwlYZTyei8tejq1rq2x9utgzs0HdkCkVaFQUvydIez8etPvjHNLYuyfmbnv62kUuhIIsY4KjFrjLfK1hPSCkb1BNeLft+6unL/CKit2U= root@alice
ssh-dss AAAAB3NzaC1kc3MAAACBANaqirTn2fWm5I0Mh62QRC0BYDaSkA9hcCUVzeup4ERmW4RPgXqfxRFzbYEsqjHrg0hg9HcOknqYFbt9GXm/OONL2URB2J/iOihqHpIh1STcyPhlqaAR1xHXHyf/4rO08dNBYuD+6qaVL9GgXiK3R46S+HwCq0d8VW82u3MzZBFBAAAAFQCSdUcc3cv+14RMDgYMWAijoVE8XQAAAIAUo+Gyo/K2yho9wZ6iGltTnMCD17ftKGnDIWL51VZ/4bXXrxPuzAHAXfxTpg2BxsJDAQGXN+06fD6nR78o2hW+V8AyFhT+owBvZoe9LKZG29Q3XmX4fwRACC7YMPmrejIeESSJVs4qya/OabeIJPxqHn4MIPbrFrtuYzANMgVRGwAAAIAMqeyBn88f+bOs95BnaFHo5AJdJZH9oWJ9M1mdU8sMQpdEa8FTHyvSZ/ajcWJ7fF6zP+DxrsgZK65IQDx3LSbltfmpr4OgnOMPKnnEY7mgCgpR33Sk4I1VxqTF3jYyKchBha6z/tNlu+XUoOJa9Ge/vYjk8uHIxxAwGm4UAvARPw== root@alice
-----END SSH HOST KEY KEYS-----
=== network info ===
if-info: lo,up,127.0.0.1,8,::1
if-info: eth0,up,10.0.2.15,24,fe80::5054:ff:fe12:3456
ip-route:default via 10.0.2.2 dev eth0 
ip-route:10.0.2.0/24 dev eth0  src 10.0.2.15 
=== datasource: ec2 net ===
instance-id: i-00001673
name: N/A
availability-zone: nova
local-hostname: alice.novalocal
launch-index: 0
=== cirros: current=0.3.5 latest=0.4.0 uptime=22.58 ===
  ____               ____  ____
 / __/ __ ____ ____ / __ \/ __/
/ /__ / // __// __// /_/ /\ \ 
\___//_//_/  /_/   \____/___/ 
   http://cirros-cloud.net


login as 'cirros' user. default password: 'cubswin:)'. use 'sudo' for root.
alice login: cirros
Password: 
$ ls -la
total 6
drwxr-xr-x    3 cirros   cirros        1024 May 15 20:43 [1m[38;5;4m[94m.[0m
drwxrwxr-x    4 root     root          1024 Feb 10  2017 [1m[38;5;4m[94m..[0m
-rw-------    1 cirros   cirros         196 May 15 20:43 .ash_history
-rwxr-xr-x    1 cirros   cirros          43 Feb 10  2017 [1m[38;5;2m[92m.profile[0m
-rwxr-xr-x    1 cirros   cirros          66 Feb 10  2017 [1m[38;5;2m[92m.shrc[0m
drwxr-xr-x    2 cirros   cirros        1024 May 15 20:42 [1m[38;5;4m[94m.ssh[0m
$ echo "hello worlsd[Kd[K[Kd" > test
$ 
login as 'cirros' user. default password: 'cubswin:)'. use 'sudo' for root.
alice login: qemu-system-x86_64: terminating on signal 2
[1m[38;5;2m[92m[38;5;4m[94m~[0m$ [K[1;24r[?1l>[24;1H[7m                                                                                [27m[24;1H
[?1049l[detached from 14517.pts-0.deploy]

Script done on Wed May 15 19:51:52 2019
